"""Phase 3: Pandas cleaning. Every decision is recorded in reports/cleaning_log.md."""
import numpy as np
import pandas as pd

from config import ATTACK_CAT_FIXES, CLEAN_PARQUET, REPORTS_DIR
from load_data import load_raw, memory_mb
from utils import banner, save_json


class CleaningLog:
    def __init__(self):
        self.steps = []

    def add(self, step, decision, rows_before, rows_after, affected=0):
        self.steps.append(dict(step=step, decision=decision, rows_before=rows_before,
                               rows_after=rows_after, affected=int(affected)))
        print(f" - {step}: {decision} (affected {int(affected):,}; rows {rows_before:,} -> {rows_after:,})")

    def write(self, path, extra_md=""):
        lines = ["# Cleaning log", "",
                 "Generated by `src/clean.py`. Dataset: UNSW-NB15 official train/test release.", "",
                 "| # | Step | Decision | Rows affected | Rows before | Rows after |",
                 "|---|------|----------|--------------:|------------:|-----------:|"]
        for i, s in enumerate(self.steps, 1):
            lines.append(f"| {i} | {s['step']} | {s['decision']} | {s['affected']:,} | "
                         f"{s['rows_before']:,} | {s['rows_after']:,} |")
        path.write_text("\n".join(lines) + "\n\n" + extra_md, encoding="utf-8")


def clean(df, log):
    n = len(df)
    feat_cols = [c for c in df.columns if c not in ("id", "split")]

    # 1. Column names
    df.columns = [c.strip().lower() for c in df.columns]
    log.add("Column names", "Header row present; names stripped and lower-cased "
            "(no NUSW feature-file mapping needed for this release)", n, n)

    # 2. Missing / unavailable fields in this release
    log.add("Unavailable fields", "srcip, dstip, sport, dsport, stime, ltime do NOT exist in the "
            "train/test release -> no epoch conversion, port coercion, hour/day features or IP analysis. "
            "Substitutes are documented in the README", n, n)

    # 3. Categorical whitespace / case
    before = df[["proto", "service", "state"]].copy()
    df["proto"] = df["proto"].astype(str).str.strip().str.lower()
    df["state"] = df["state"].astype(str).str.strip().str.upper()
    df["service"] = df["service"].astype(str).str.strip().str.lower()
    changed = int((before != df[["proto", "service", "state"]]).any(axis=1).sum())
    log.add("Categorical text", "Stripped whitespace; proto/service lower-case, state upper-case", n, n, changed)

    n_dash = int((df["service"] == "-").sum())
    df["service"] = df["service"].replace("-", "none")
    log.add("Service '-'", "'-' means no application service was identified -> recoded to 'none'", n, n, n_dash)

    # 4. attack_cat: fill + canonical labels
    n_na = int(df["attack_cat"].isna().sum() + (df["attack_cat"].astype(str).str.strip() == "").sum())
    raw_cat = df["attack_cat"].fillna("Normal").astype(str).str.strip()
    raw_cat = raw_cat.replace("", "Normal")
    fixed = raw_cat.str.lower().map(ATTACK_CAT_FIXES).fillna(raw_cat)
    n_fixed = int((fixed != raw_cat).sum())
    df["attack_cat"] = fixed
    log.add("attack_cat missing", "NaN/blank attack_cat filled with 'Normal'", n, n, n_na)
    log.add("attack_cat labels", "Stripped + mapped spelling variants (e.g. 'Backdoors'->'Backdoor')", n, n, n_fixed)

    # 5. label consistency
    mism = (df["label"] == 0) != (df["attack_cat"] == "Normal")
    log.add("Label consistency", "Checked label==0 <=> attack_cat=='Normal'; mismatches flagged "
            "(flag_label_mismatch)", n, n, mism.sum())
    df["flag_label_mismatch"] = mism.astype("int8")

    # 6. Negative / impossible values
    num_cols = df.select_dtypes(include="number").columns.drop(["id", "label"])
    neg = (df[num_cols] < 0).any(axis=1)
    log.add("Negative values", "Scanned all numeric columns for negatives; flagged (flag_negative)", n, n, neg.sum())
    df["flag_negative"] = neg.astype("int8")

    bad_ttl = (df["sttl"] > 255) | (df["dttl"] > 255)
    log.add("TTL range", "TTL must be 0-255; out-of-range rows flagged", n, n, bad_ttl.sum())

    bad_ftp = df["is_ftp_login"] > 1
    df["flag_invalid_ftp_login"] = bad_ftp.astype("int8")
    df.loc[bad_ftp, "is_ftp_login"] = 1
    log.add("is_ftp_login", "Binary feature had values 2-4; capped to 1 and flagged "
            "(flag_invalid_ftp_login)", n, n, bad_ftp.sum())

    zero_dur = df["dur"] <= 0
    df["flag_zero_duration"] = zero_dur.astype("int8")
    log.add("Zero duration", "dur==0 kept (single-packet flows) but flagged; rate features use dur "
            "clipped at 1 microsecond", n, n, zero_dur.sum())

    # 7. Duplicates - flag, do NOT drop
    dup = df.duplicated(subset=feat_cols + ["split"], keep="first")
    df["is_duplicate"] = dup.astype("int8")
    log.add("Duplicates (within split)", "Feature-identical rows (ignoring id) FLAGGED, not removed: "
            "dropping them would change the official benchmark split, and repeated identical flows are "
            "genuine traffic (e.g. scripted Generic/Exploit attacks)", n, n, dup.sum())

    train_keys = pd.util.hash_pandas_object(df.loc[df["split"] == "train", feat_cols], index=False)
    test_keys = pd.util.hash_pandas_object(df.loc[df["split"] == "test", feat_cols], index=False)
    cross = test_keys.isin(set(train_keys)).sum()
    df["in_both_splits"] = 0
    df.loc[test_keys.index[test_keys.isin(set(train_keys))], "in_both_splits"] = 1
    df["in_both_splits"] = df["in_both_splits"].astype("int8")
    log.add("Train/test overlap", "Test rows whose features exactly match a train row flagged "
            "(in_both_splits) - reported as an evaluation caveat", n, n, cross)

    # 8. Derived features
    dur_safe = df["dur"].clip(lower=1e-6).astype("float64")
    df["is_attack"] = df["label"].astype("int8")
    df["total_bytes"] = (df["sbytes"].astype("int64") + df["dbytes"].astype("int64"))
    df["total_pkts"] = (df["spkts"].astype("int32") + df["dpkts"].astype("int32"))
    df["bytes_per_sec"] = (df["total_bytes"] / dur_safe).astype("float32")
    df["pkts_per_sec"] = (df["total_pkts"] / dur_safe).astype("float32")
    df["byte_ratio"] = (df["sbytes"] / (df["dbytes"] + 1)).astype("float32")
    df["src_byte_share"] = (df["sbytes"] / df["total_bytes"].clip(lower=1)).astype("float32")
    df["bytes_per_pkt"] = (df["total_bytes"] / df["total_pkts"].clip(lower=1)).astype("float32")
    log.add("Derived features", "Added is_attack, total_bytes, total_pkts, bytes_per_sec, pkts_per_sec, "
            "byte_ratio=sbytes/(dbytes+1), src_byte_share, bytes_per_pkt. hour/day NOT possible "
            "(no timestamps)", n, n)

    # 9. Keys and dtypes
    df = df.rename(columns={"id": "orig_id"})
    df.insert(0, "flow_id", np.arange(1, len(df) + 1, dtype="int32"))
    for c in ["proto", "service", "state", "attack_cat", "split"]:
        df[c] = df[c].astype("category")
    log.add("Keys & dtypes", "orig_id kept (per-file id); new global flow_id; categoricals stored as "
            "category; numerics downcast", n, len(df))
    return df


def run():
    banner("PHASE 3 - CLEANING")
    df = load_raw()
    mem_before = memory_mb(df)
    log = CleaningLog()
    df = clean(df, log)
    df.to_parquet(CLEAN_PARQUET, index=False)

    summary = {
        "rows_before": log.steps[0]["rows_before"], "rows_after": len(df), "cols_after": df.shape[1],
        "memory_mb_before": mem_before, "memory_mb_after": memory_mb(df),
        "duplicates_flagged": int(df["is_duplicate"].sum()),
        "duplicates_by_split": df.groupby("split", observed=True)["is_duplicate"].sum().to_dict(),
        "test_rows_seen_in_train": int(df["in_both_splits"].sum()),
        "invalid_ftp_login": int(df["flag_invalid_ftp_login"].sum()),
        "zero_duration": int(df["flag_zero_duration"].sum()),
        "label_mismatch": int(df["flag_label_mismatch"].sum()),
        "negatives": int(df["flag_negative"].sum()),
    }
    save_json(summary, "cleaning_summary")
    extra = (
        "## Summary\n\n"
        f"- Rows before: {summary['rows_before']:,}; rows after: {summary['rows_after']:,} "
        "(no rows dropped - problems are flagged so analysts can filter them).\n"
        f"- Memory: {summary['memory_mb_before']} MB raw (downcast) -> {summary['memory_mb_after']} MB cleaned "
        "(categoricals).\n"
        f"- Duplicates flagged: {summary['duplicates_flagged']:,} {summary['duplicates_by_split']}.\n"
        f"- Test rows identical to a train row: {summary['test_rows_seen_in_train']:,}.\n"
        f"- Output: `data/processed/flows_clean.parquet` ({df.shape[1]} columns).\n"
    )
    log.write(REPORTS_DIR / "cleaning_log.md", extra)
    print(f"Saved {CLEAN_PARQUET.name}: {df.shape}, {summary['memory_mb_after']} MB")
    return summary


if __name__ == "__main__":
    run()
