"""Phase 4: database layer (SQLite via SQLAlchemy; PostgreSQL-ready).

PostgreSQL is not installed on the build machine, so the default is a single-file
SQLite database at data/processed/nb15_threat.db. To use PostgreSQL instead, set
the environment variable NB15_DB_URL, e.g.
    postgresql+psycopg2://user:password@localhost:5432/nb15
(schema.sql uses portable types; executescript-style loading would need psql).
"""
import os
import re

import pandas as pd
from sqlalchemy import create_engine, text

from config import ATTACK_TYPES, CHUNK_SIZE, CLEAN_PARQUET, DB_URL, EXPORT_DIR, REPORTS_DIR, SQL_DIR
from utils import banner, save_json

SQL_EXPORT_DIR = EXPORT_DIR / "sql"
SQL_EXPORT_DIR.mkdir(parents=True, exist_ok=True)


def get_engine():
    return create_engine(os.environ.get("NB15_DB_URL", DB_URL))


def run_script(engine, sql_text):
    """Execute a multi-statement SQL script."""
    raw = engine.raw_connection()
    try:
        raw.executescript(sql_text)  # sqlite3 API
        raw.commit()
    finally:
        raw.close()


def severity_level(w):
    return "None" if w == 0 else "Critical" if w >= 0.9 else "High" if w >= 0.7 else "Medium" if w >= 0.5 else "Low"


def dim_attack_type():
    return pd.DataFrame([
        {"attack_cat": k, "severity_weight": w, "severity_level": severity_level(w), "description": d}
        for k, (w, d) in ATTACK_TYPES.items()
    ])


def load_flows(engine, df, chunksize=CHUNK_SIZE):
    """Append the cleaned flows to network_flows in chunks."""
    out = df.copy()
    for c in out.select_dtypes(include="category").columns:
        out[c] = out[c].astype(str)
    total = 0
    for start in range(0, len(out), chunksize):
        part = out.iloc[start:start + chunksize]
        part.to_sql("network_flows", engine, if_exists="append", index=False)  # executemany: fastest on SQLite
        total += len(part)
        print(f"   loaded {total:,}/{len(out):,}")
    return total


def parse_named_queries(path):
    """Split analysis_queries.sql into [(name, desc, sql)] using '-- name:' markers."""
    txt = path.read_text(encoding="utf-8")
    blocks = re.split(r"^-- name:\s*", txt, flags=re.M)[1:]
    queries = []
    for b in blocks:
        lines = b.strip().splitlines()
        name = lines[0].strip()
        desc = lines[1].replace("-- desc:", "").strip() if lines[1].startswith("-- desc:") else ""
        sql = "\n".join(l for l in lines[2:] if not l.startswith("--")).strip().rstrip(";")
        queries.append((name, desc, sql))
    return queries


def view_stage(stage):
    """Return the SQL for one '-- @stage:' section of views.sql."""
    txt = (SQL_DIR / "views.sql").read_text(encoding="utf-8")
    parts = re.split(r"^-- @stage:\s*(\w+)\s*$", txt, flags=re.M)
    sections = dict(zip(parts[1::2], parts[2::2]))
    return sections[stage]


def run_queries(engine, write_md=True):
    results = {}
    md = ["# SQL analysis results", "",
          "Generated by `src/db.py` from `sql/analysis_queries.sql` (SQLite). "
          "Full CSVs: `powerbi/exports/sql/`.", ""]
    with engine.connect() as con:
        for name, desc, sql in parse_named_queries(SQL_DIR / "analysis_queries.sql"):
            res = pd.read_sql(text(sql), con)
            res.to_csv(SQL_EXPORT_DIR / f"{name}.csv", index=False)
            results[name] = res
            md += [f"## {name}", f"_{desc}_", "", res.head(15).to_markdown(index=False), ""]
            print(f"   {name}: {len(res)} rows")
    if write_md:
        (REPORTS_DIR / "sql_results.md").write_text("\n".join(md), encoding="utf-8")
    return results


def write_table(df, name, engine=None, if_exists="replace"):
    engine = engine or get_engine()
    out = df.copy()
    for c in out.select_dtypes(include="category").columns:
        out[c] = out[c].astype(str)
    out.to_sql(name, engine, if_exists=if_exists, index=False, chunksize=CHUNK_SIZE)


def run():
    banner("PHASE 4 - DATABASE + SQL")
    engine = get_engine()
    df = pd.read_parquet(CLEAN_PARQUET)

    run_script(engine, (SQL_DIR / "schema.sql").read_text(encoding="utf-8"))
    print(" - schema created")
    dim_attack_type().to_sql("dim_attack_type", engine, if_exists="append", index=False)

    loaded = load_flows(engine, df)
    with engine.connect() as con:
        db_rows = con.execute(text("SELECT COUNT(*) FROM network_flows")).scalar()
        db_attacks = con.execute(text("SELECT SUM(label) FROM network_flows")).scalar()
    assert db_rows == len(df) == loaded, f"Row count mismatch: parquet={len(df)}, db={db_rows}"
    assert db_attacks == int(df["label"].sum()), "Attack count mismatch"
    print(f" - verified row count: parquet {len(df):,} == db {db_rows:,}; attacks {db_attacks:,}")

    with engine.begin() as con:
        con.execute(text("""
            INSERT INTO segment_summary
            SELECT proto, service, state, COUNT(*), SUM(label), AVG(label),
                   COUNT(DISTINCT CASE WHEN label = 1 THEN attack_cat END),
                   AVG(sbytes), AVG(rate)
            FROM network_flows GROUP BY proto, service, state"""))
    run_script(engine, view_stage("base"))
    print(" - segment_summary populated, base views created")

    results = run_queries(engine)
    with engine.connect() as con:
        for v in ["v_kpi_overview", "v_attack_by_type", "v_protocol_service_matrix",
                  "v_attack_by_state", "v_attack_by_duration_bin"]:
            pd.read_sql(text(f"SELECT * FROM {v}"), con).to_csv(SQL_EXPORT_DIR / f"{v}.csv", index=False)
    summary = {"db_url": str(engine.url), "rows_loaded": int(db_rows), "attack_rows": int(db_attacks),
               "queries_run": len(results)}
    save_json(summary, "db_summary")
    print(f"Ran {len(results)} queries; CSVs in {SQL_EXPORT_DIR}")
    return results


if __name__ == "__main__":
    run()
